service: notifcations
frameworkVersion: '2'

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs14.x
  region: eu-west-1

functions:
  notification:
    handler: "./src/sendMessage.sendMessage"
    description: "Receives an SQS message and sends on the notification"
    events:
      - sqs:
          arn: !GetAtt
            - NotificationsQueue
            - Arn
          batchSize: 1
          enabled: true
      - sqs:
          arn: !GetAtt
            - NotificationsDeadLetterQueue
            - Arn
          batchSize: 1
          enabled: false

resources:
  Resources:
    NotificationsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-notifications-queue
        VisibilityTimeout: 180
        RedrivePolicy:
          deadLetterTargetArn: !GetAtt
            - NotificationsDeadLetterQueue
            - Arn
          maxReceiveCount: 3
    
    NotificationsDeadLetterQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: ${self:provider.stage}-notifications-dead-letter-queue
        VisibilityTimeout: 180
        MessageRetentionPeriod: 1209600
